'''
to validate the observation dates of historic years shown in the seasonal charts generated by the charting api
'''
from mosaic_api_examples import prepare_inputs_for_api, example_kwargs_dict
from constants import PROD
from mosaic_api_utils import get_any_api

env = PROD
api_name = 'getExpiry'
url, params, method = prepare_inputs_for_api(api_name, env, kwargs_dict=example_kwargs_dict)
response = get_any_api(url, params)
print()
pass




